[libraries]
apache-commons-lang3 = { module = "org.apache.commons:commons-lang3", version = "3.10" }
apache-commons-io = { module = "commons-io:commons-io", version = "2.6" }
apache-commons-collections4 = { module = "org.apache.commons:commons-collections4", version = "4.4" }
dataFaker = { module = "net.datafaker:datafaker", version = "1.3.0" }
easyTuples = { module = "io.github.easytuples:easy-tuples", version = "1.0.0" }
guava = { module = "com.google.guava:guava", version = "31.1-jre" }
lombok = { module = "org.projectlombok:lombok", version = "1.18.38" }
postgresql = { module = "org.postgresql:postgresql" }
tess4j = { module = "net.sourceforge.tess4j:tess4j", version = "5.16.0" }

[bundles]
apache-commons = [ "apache-commons-lang3", "apache-commons-io", "apache-commons-collections4" ]

